
```{r}
clust_1 =  c(
  "Tcfcp2l1"
  ,"Tbx3"
  ,"Klf4"
  ,"Bmp4"
  ,"Nr5a2"
  ,"Wdr5"
  ,"Nanog"
  ,"Zfp57"
  ,"Zfp42.1"
  ,"Esrrb"
  ,"Tcl1"
  ,"Nr0b1"
)



clust_2 = c(
  "Fbxo15",
  "Sall4"
  ,"Lin28a"
  ,"Jarid2"
  ,"Dppa4"
  ,"Rest"
  #,"Trim28"
  ,"Utf1"
  ,"Ctr9"
  ,"Zscan10"
  ,"Cbx1"
  ,"Mbd3"
  ,"Ctcf"
  ,"Zfp281"
  ,"Dppa2"
)


clust_3 = c( "Pou5f1"
                     ,"Sox2"
                     ,"Stat3"
                     ,"Cdx2"
                     ,"FoxA"
                     ,"Smad3"
                     ,"smad4"
                     ,"snad2"
                     ,"eomes"
                     ,"cdx3"
                     ,"lef1"
                     ,"sox17"
                     ,"Tet1"
                     ,"pu1"
                     ,"pu.1"
                     ,"pu"
                     ,"gata2"
                     ,"gata6"
                     ,"gata4"
)

markers = c(clust_3,clust_2,clust_1)
names(markers) = markers
```

```{r}
loadCountsRds = function(file)
{
  curr_path = file.path(working_dir, file)
  if(file.exists(curr_path))
  {
    expr_out<-readRDS(file  =  curr_path)
    return (expr_out)
  }else{
    cat("Unable to find ", curr_path)
    cat("\tPlease, change working dir or set 'clean  =  TRUE'")
  }
}

load_sce = function(sce)
{
  if(length(table(get_types(colnames(sce)))) < ncol(sce)/2)
  {

  }else
    if(!is.null(sce$Type))
    {
      colnames(sce) = types2names(sce$Type)
    }else
      if(!is.null(sce$cell_type1))
      {
        colnames(sce) = types2names(sce$cell_type1)
      }
  curr_assay <-tryCatch(counts(sce), error  =  function(e) {NULL})

  if(is.null(curr_assay))
  {
    curr_assay = rel2abs(exprs(sce))
    print("sce_exprs")
  }else{
    print("sce_counts")
  }
  return(curr_assay)
}
# 
# # curr_assay = as.matrix(read.table("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\NanoString\\expressionTableDedupQC.csv"))
# # curr_proc = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\NanoString\\", counts_mtx  =  curr_assay, markers  =  markers, impute  =  T)
# # 
# # curr_assay = rel2abs(as.matrix(read.table("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\idc.tpm.txt")))
# # curr_proc = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\", counts_mtx  =  curr_assay, markers  =  markers)
# # 
# # curr_assay = as.data.frame(read.table("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\SC3\\patient1-raw.txt", header = TRUE, sep  =  "\t"))
# # 
# # 
# # curr_proc = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\", counts_mtx  =  curr_assay, markers  =  markers)
# 
# old = readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\Svet\\old.rds")
# new = readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\Svet\\new.rds")
# 
# 
# old = load_sce(old)
# new = load_sce(new)
# 
# 
# 
# curr_proc = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\Svet\\", counts_mtx  =  old, markers  =  markers)
# curr_proc1 = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\Svet\\", counts_mtx  =  new, markers  =  markers)

curr_assay = as.matrix(read.table("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\idc.counts.txt"))
curr_proc = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\", counts_mtx  =  curr_assay, markers  =  markers)

curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\biase.rds"))
curr_proc0 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/biase/", counts_mtx  =  curr_assay, markers  =  markers)

curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\deng-reads.rds"))
curr_proc1 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/deng-reads/", counts_mtx  =  curr_assay, markers  =  markers)



curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\fan.rds"))
curr_proc2 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/fan/", counts_mtx  =  curr_assay, markers  =  markers)

curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\goolam.rds"))
curr_proc3 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/goolam/", counts_mtx  =  curr_assay, markers  =  markers)

curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\klein.rds"))
curr_proc4 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/klein/", counts_mtx  =  curr_assay, markers  =  markers)

curr_assay = load_sce(readRDS(file  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\outer\\kolodziejczyk.rds"))
curr_proc5 = full_preprocess(working_path  =  "F:/bioinf/Sk/SingleCellRNASeq/outer/kolodziejczyk/", counts_mtx  =  curr_assay, markers  =  markers)

```


```{r}
# exprs_list = c("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784310\\cell.counts.matrices.rds",
#                "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784313\\cell.counts.matrices.rds",
#                "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784314\\cell.counts.matrices.rds",
#                "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784315\\cell.counts.matrices.rds")
# 
# 
# d0 = load_velocity_mtx("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784310\\cell.counts.matrices.rds")
# d2 = load_velocity_mtx("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784313\\cell.counts.matrices.rds")
# d4 = load_velocity_mtx("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784314\\cell.counts.matrices.rds")
# d7 = load_velocity_mtx("F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine\\SRR1784315\\cell.counts.matrices.rds")
# 
# 
# genes_all = unique(c(rownames(d0), rownames(d2), rownames(d4), rownames(d7)))
# 
# genes_zero_d0 = setdiff(genes_all, rownames(d0))
# genes_zero_d2 = setdiff(genes_all, rownames(d2))
# genes_zero_d4 = setdiff(genes_all, rownames(d4))
# genes_zero_d7 = setdiff(genes_all, rownames(d7))
# 
# d0 = add_zero_genes(d0, genes_zero_d0)
# colnames(d0) = sapply(1:ncol(d0), function(x) {return(paste0("d0.", x))})
# d2 = add_zero_genes(d2, genes_zero_d2)
# colnames(d2) = sapply(1:ncol(d2), function(x) {return(paste0("d2.", x))})
# d4 = add_zero_genes(d4, genes_zero_d4)
# colnames(d4) = sapply(1:ncol(d4), function(x) {return(paste0("d4.", x))})
# d7 = add_zero_genes(d7, genes_zero_d7)
# colnames(d7) = sapply(1:ncol(d7), function(x) {return(paste0("d7.", x))})
# 
# d = cbind(d0[order(rownames(d0)),], d2[order(rownames(d2)),], d4[order(rownames(d4)),], d7[order(rownames(d7)),])
# 
# final_exprs = full_preprocess(working_path  =  "F:\\bioinf\\Sk\\SingleCellRNASeq\\reads\\klein\\mine", counts_mtx  =  d, markers  =  markers)

```
