```{r}
ipak <- function(pkg, repository = c("CRAN", "Bioconductor", "github")) {
    #new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    new.pkg <- pkg
    if (length(new.pkg)) {
        if (repository == "CRAN") {
            install.packages(new.pkg, dependencies = TRUE)
        }
        if (repository == "Bioconductor") {
            source("https://bioconductor.org/biocLite.R")
            biocLite(new.pkg, dependencies = TRUE, ask = FALSE, type="source")
        }
        if (repository == "github") {
            devtools::install_github(pkg, build_vignettes = FALSE, force = TRUE) 
        }
    }
}

#CRAN packages
cranpackages <- c("data.table", "devtools")
ipak(cranpackages, repository = "CRAN")

# BIOCONDUCTOR packages
biocpackages <- c("scater", "BiocGenerics", "survival","DelayedArray","scran","biomaRt","monocle","edgeR","tools","pastecs","plotrix","FNN","rsvd","Matrix","RColorBrewer","M3Drop","VennDiagram","MAST","ggplot2","GenomicRanges","ReactomePA","clusterProfiler", "pathview", "limSolve")
ipak(biocpackages, repository = "Bioconductor")

# GITHUB packages
githubpackages <- c("mohuangx/SAVER", "satijalab/seurat")
ipak(githubpackages, repository = "github")
 
```


```{r}
devtools::install_github("jingshuw/descend")
```

